### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by ilDon** [DevClad-Inc/devclad#92]
Hello DevClad team!
I've received the beta update and tried to login, but I could not.
I first tried with my email (the one where I received the newsletter) and PWD, but I must have forgotten my password, so I've clicked the "Forgot password link", requested a link, but never got an email.
Then I tried to log in with GitHub. the OAuth flow did complete successfully, it does say "Authenticated", but I am redirected to the login page, and I can't find any way to get past the login page

**Comment by arthtyagi** [comment]
Hey, I understand the issue but it's not an issue with the technical implementation. So, I'll be closing this issue and instead starting a discussion.

**Comment by arthtyagi** [comment]
Oh and also, Github is only for login not for creating accounts (there's info text on the page as well now).

With that out of the way, are you sure created an account on DevClad (https://app.devclad.com/signup)?
